backend:
  name: git-gateway
  repo: AsarMichil/hoffman-website
  branch: main 
  
publish_mode: editorial_workflow

media_folder: "static/img" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: "Bio" 
            name: bio
            widget: object
            fields: 
              - {label: "BigText", name: "bigText", widget: string}
              - {label: "Text", name: "para1", widget: "text"}
      - file: "site/content/books/_index.md"
        label: "Books Page"
        name: "books"
        widget: "object"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: "Books"
            name: "books"
            fields:
              - {label: Heading, name: heading1, widget: string}
              - {label: Text, name: para1, widget: text}
              - {label: Image, name: bookimage1, widget: image}
              - {label: Heading, name: heading2, widget: string}
              - {label: Text, name: para2, widget: text}
              - {label: Image, name: bookimage2, widget: image}
              - {label: Heading, name: heading3, widget: string}
              - {label: Text, name: para3, widget: text}
              - {label: Image, name: bookimage3, widget: image}
          - label: "Publications"
            name: "publications"
            widget: "object"
            fields: 
              - {label: Heading, name: pheading, widget: string}
              - {label: Text, name: blurb, widget: text}
              - label: "Image1"
                name: image1
                widget: "object"
                fields: 
                - {label: Image, name: image, widget: image}
                - {label: Alt, name: alt, widget: string}
                - {label: Link, name: link, widget: string}
              - label: "Image2"
                name: image2
                widget: "object"
                fields: 
                - {label: Image, name: image, widget: image}
                - {label: Alt, name: alt, widget: string}
                - {label: Link, name: link, widget: string}
              - label: "Image3"
                name: image3
                widget: "object"
                fields: 
                - {label: Image, name: image, widget: image}
                - {label: Alt, name: alt, widget: string}
                - {label: Link, name: link, widget: string}  
              
